project:
  type: website

description-meta: "Quarto Website adapted by Mauricio Moreno, PhD"
author-meta: "Mauricio Moreno, PhD"

website:
  title: "Mauricio Moreno"
  image: files/images/icon1_nb.png
  favicon: files/images/icon1_nb.png
  site-url: https://mauricio-moreno.net
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Publications
        
        href: publications.qmd
    right: 
      - icon: github
        href: https://github.com/mmorenozam
        target: _blank
  page-navigation: true
  
  page-footer:
    left: "[Mauricio Moreno](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>"
    right: "Created in Quarto"

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: 
      - styles.css
    toc: true
    extensions:
      - banner-override

freeze: auto
# format:
#   html:
#     theme:
#       - cosmo
#       - brand
#     css: styles.css
#     toc: true



