---
title: "Publications"
description-meta: "Information, pdfs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---

<!--Include academic icons or buttons-->
{{< include /files/includes/_academic.qmd >}}

J. Langbein. **M. Moreno-Zambrano** and K. Siebert. [How do goats “read" 2D-images of familiar and
unfamiliar conspecifics?.](https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2023.1089566/full) *Frontiers in Psychology*, 14, 2023. <span class="__dimensions_badge_embed__" data-doi="10.3389/fpsyg.2023.1089566" data-style="large_rectangle"></span> <div data-badge-popover="right" data-badge-type="1" data-doi="10.3389/fpsyg.2023.1089566" data-hide-no-mentions="true" class="altmetric-embed"></div>     

<center><hr style="width:50%"></center>

**M. Moreno-Zambrano**, M. S. Ullrich, and M-T. Hütt. [Exploring cocoa bean fermentation mechanisms
by kinetic modelling.](https://royalsocietypublishing.org/rsos/article/9/2/210274/96539/Exploring-cocoa-bean-fermentation-mechanisms-by) Royal Society Open Science, 9(2), 2022. <span class="__dimensions_badge_embed__" data-doi="10.1098/rsos.210274" data-style="large_rectangle"></span> <div data-badge-popover="right" data-badge-type="1" data-doi="10.1098/rsos.210274" data-hide-no-mentions="true" class="altmetric-embed"></div>     

<center><hr style="width:50%"></center>

R. Megias-Perez, **M. Moreno-Zambrano**, B. Behrends, M. Corno, and N. Kuhnert. [Monitoring the
changes of low molecular weight carbohydrates in cocoa beans during spontaneous fermentation: a chemometric
and kinetic approach.](https://www.sciencedirect.com/science/article/abs/pii/S0963996919307513) Food Research International, 2019. <span class="__dimensions_badge_embed__" data-doi="10.1016/j.foodres.2019.108865" data-style="large_rectangle"></span> <div data-badge-popover="right" data-badge-type="1" data-doi="10.1016/j.foodres.2019.108865" data-hide-no-mentions="true" class="altmetric-embed"></div>

<center><hr style="width:50%"></center>

**M. Moreno-Zambrano**, S. Grimbs, M. S. Ullrich, and M-T. Hütt. [A mathematical model of cocoa
bean fermentation.](https://royalsocietypublishing.org/rsos/article/5/10/180964/93960/A-mathematical-model-of-cocoa-bean) Royal Society Open Science, 5(10), 2018. <span class="__dimensions_badge_embed__" data-doi="10.1098/rsos.180964" data-style="large_rectangle"></span> <div data-badge-popover="right" data-badge-type="1" data-doi="10.1098/rsos.180964" data-hide-no-mentions="true" class="altmetric-embed"></div>

<center><hr style="width:50%"></center>

F. J. Flores, S. M. Marek, J. A. Anderson, T. K. Mitchell, **M. Moreno-Zambrano**, and N. R. Walker.
[Reactive oxygen species production and alternative hosts of spring dead spot-causing fungi.](https://onlinelibrary.wiley.com/doi/full/10.2134/itsrj2016.06.0480) International
Turfgrass Society and ACSESS, 13:213–224, 2017. <span class="__dimensions_badge_embed__" data-doi="10.2134/itsrj2016.06.0480" data-style="large_rectangle"></span> <div data-badge-popover="right" data-badge-type="1" data-doi="10.2134/itsrj2016.06.0480" data-hide-no-mentions="true" class="altmetric-embed"></div>
